import Head from "next/head";
import Image from "next/image";
import styles from '../../styles/Home.module.css'

function Documentation() {
    return (
        <div>
            <Head>
                <title>Documentation</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>Documentation</h1>
                <p className={styles.description}>
                    This document contains all the {' '}
                    <a href='/' className={styles.code}>MADEA's</a>
                    domentation.
                </p>
            </main>
        </div>
    )
};

export default Documentation;