import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';

function Products() {
    return (
        <div>
            <Head>
                <title>Products</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head> 
            <main className={styles.main}>
                <h1 className={styles.title} >Products</h1>
                <p className={styles.description}>
                    This document contains all the {' '}
                    <a href='/' className={styles.code}>MADEA's</a>
                    products.
                </p>
                <div className={styles.gridProducts}>
                    <a href="" className={styles.card}>
                        <h2>Chispas &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>
                    <a href="" className={styles.card}>
                        <h2>CuadriMix &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>
                    <a href="" className={styles.card}>
                        <h2>TrailMix &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>
                </div>
            </main>
        </div>
    )
  }
  
  export default Products;